### PR TITLE
print() is a function in Python 3

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by tavianator** [comment]
I see you've already directed this upstream through https://github.com/erkyrath/cheapglk/pull/5.  We'll import it from there if and when it's merged.  Thanks!

**Comment by cclauss** [comment]
Merged in upstream.

**Comment by cclauss** [comment]
@tavianator This was merged in https://github.com/erkyrath/cheapglk/pull/5 and it is a ___syntax error___.

**Comment by tavianator** [comment]
Thanks for the ping: https://github.com/Microsoft/TextWorld/pull/117

**Pull request closed without merging**
