### PR TITLE
game: Add a version number to the serialization format

### PR DESCRIPTION
**Pull request by tavianator**

### CODE REVIEW

**Comment by MarcCote** [comment]
Should we do the compiled game versioning in this PR? I'm thinking of adding a text command `tw-version` in the Inform7 code (world2inform7.py).

**Comment by tavianator** [comment]
@MarcCote Good call, I added a `tw-print version` command.  I didn't add any code that checks it yet because I want to remain compatible with old games for now.  (Is there an easy way to try a command that may or may not exist?)

**Comment by MarcCote** [comment]
I guess we could issue the command `tw-print version` and check for the feedback?
```
> tw-print version
I didn't understand that sentence.
```

**Comment by tavianator** [comment]
@MarcCote Done as you suggested.

**Pull request merged**
