### PR TITLE
Version + Changelog

### PR DESCRIPTION
**Pull request by MarcCote**
- Bump version number
- Update changelog

### CODE REVIEW

**Comment by MarcCote** [comment]
@tavianator Great. I'll let you tag the commit, push the release to pypi and re-build the docs. Thanks.

**Comment by tavianator** [comment]
Sounds good!  I have one more PR before releasing, just to add the script I use for building the binary Linux packages.

**Comment by leonoverweel** [comment]
Great to see this going up so fast, thanks for being so on top of this!

**Comment by MarcCote** [comment]
Thanks for bringing up the issue.

**Pull request merged**
