### PR TITLE
Replacing local version of Jericho in favor of the one found on Pypi

### PR DESCRIPTION
**Pull request by MarcCote**
This PR drops the local version of [Jericho](https://github.com/Microsoft/jericho) in favor of the version found on Pypi.

This PR needs the following PR https://github.com/Microsoft/jericho/pull/1 to be merged first. Also, a new release would need to be pushed to Pypi.

### CODE REVIEW

**Comment by MarcCote** [comment]
@tavianator I've split the changes over two commits:

- 854462a: removing Jericho files
- d660482: using Jericho found on Pypi + add special command `tw-print max_score` + unit tests

**Comment by MarcCote** [comment]
Hi @mhauskn, are you planning on Jericho supporting OSX? If you want, I think @tavianator can help with that.

**Comment by mhauskn** [comment]
Yes, it would be great to support OSX. @tavianator do you have any tips for this?

**Comment by tavianator** [comment]
@mhauskn The easiest way would be to build libfrotz as a Python extension with
```python
ext_modules=[Extension('jericho.frotz', ['frotz/src/common/buffer.c', ...])]
```

Then it will automatically detect that the wheel should be architecture-specific.  You can use Azure Pipelines to automatically build Linux/Windows/macOS builds.

**Comment by MarcCote** [comment]
@tavianator all tests have passed.

**Pull request merged**
