### PR TITLE
Disable Inform7 debugging commands by default

### PR DESCRIPTION
**Pull request by MarcCote**
This PR makes sure we cannot use the Inform7 testing commands by default. One can enable them by setting the environment variable `TEXTWORLD_I6_DEBUG=True`.

This PR adds a modified version of `Actions.i6t` so we can still get the Inform7 action events that are used for our state tracking.

### CODE REVIEW

**Comment by MarcCote** [comment]
I forgot that Jericho uses the test commands `tree` and `scope` :(

**Comment by MarcCote** [comment]
@mhauskn looking at the Jericho's code, you need the `tree` command only to get the id of the EndOfObject and `scope` to get the id of the player? If so, maybe I can come up with a special `tw-***` command that gives you that information directly.

**Comment by mhauskn** [comment]
Yes, I think that would work.

**Comment by MarcCote** [comment]
I've added two special commands `tw-print player id` and `tw-player EndOfObject id` to be used by Jericho. See https://github.com/Microsoft/jericho/pull/9 which need to be merged before this one.

**Comment by MarcCote** [comment]
All tests are green :+1:

**Comment by MarcCote** [comment]
@tavianator I've added a comment explaining the changes made to `Actions.i6t` and a link to the original.

**Comment by tavianator** [comment]
`test_jericho.build_test_game` segfaults on macOS now, any idea what changed?

**Comment by MarcCote** [comment]
Yes, @mhauskn pushed a fix for memory corruption error. He's now adding macOS to Jericho's Travis and I'm guessing he will look at the segfault error after.

**Comment by MarcCote** [comment]
Alright, back on track.

**Pull request merged**
